/* Auto-generated by tools/gen_pico_atlases.py — do not edit */
#pragma once
#include <stdint.h>
#define ATLAS_ISO_MANSION_W 768
#define ATLAS_ISO_MANSION_H 128
extern const uint8_t atlas_iso_mansion_rgba[393216];
