/* Auto-generated by tools/gen_pico_atlases.py — do not edit */
#pragma once
#include <stdint.h>
#define ATLAS_ISO_ACTORS_W 160
#define ATLAS_ISO_ACTORS_H 64
extern const uint8_t atlas_iso_actors_rgba[40960];
