/* Auto-generated by tools/gen_pico_atlases.py — do not edit */
#pragma once
#include <stdint.h>
#define ATLAS_ISO_TILES_W 256
#define ATLAS_ISO_TILES_H 192
extern const uint8_t atlas_iso_tiles_rgba[196608];
