/* Auto-generated by tools/gen_pico_atlases.py — do not edit */
#pragma once
#include "atlas_iso_tiles.h"
#include "atlas_iso_actors.h"
#include "atlas_iso_mansion.h"
#include "atlas_chars.h"
#include "atlas_base.h"
