#!/usr/bin/env python3
"""
gen_pico_atlases.py — convert PNG atlases to C source + header files for
the Raspberry Pi Pico build.

Each atlas is stored as a const uint8_t array (RGBA8888) in flash via XIP.
hal_pico.c's hal_image_load_rgba() returns a pointer directly into these
flash arrays — no runtime PNG decoding, no heap allocation.

Usage:
    python3 tools/gen_pico_atlases.py <project_root>

Output (created/overwritten):
    src/pico_assets/atlas_iso_tiles.h / .c
    src/pico_assets/atlas_chars.h / .c
    src/pico_assets/pico_atlases.h   ← central include

Flash budget check is printed at the end.
"""

import os
import sys
from pathlib import Path
from PIL import Image


ATLASES = [
    ("atlas_iso_tiles",   "build/assets_iso_tiles.png"),
    ("atlas_chars",       "build/assets_chars.png"),
    # Removed: mansion, base, and iso actors are future features
    # ("atlas_iso_mansion", "assets/assets_iso_mansion.png"),
    # ("atlas_iso_actors",  "assets/assets_iso_actors.png"),
    # ("atlas_base",        "assets/assets_base.png"),
]

BYTES_PER_LINE = 32   # C source line width in bytes — balance readability vs file size


def gen_atlas(name: str, src_png: Path, out_dir: Path) -> int:
    """Generate name.h and name.c; return raw byte count."""
    img  = Image.open(src_png).convert("RGBA")
    w, h = img.size
    data = img.tobytes()            # flat RGBA8888 bytes
    n    = len(data)

    guard = name.upper()

    # --- header ---
    hpath = out_dir / f"{name}.h"
    with open(hpath, "w") as f:
        f.write(f"/* Auto-generated by tools/gen_pico_atlases.py — do not edit */\n")
        f.write(f"#pragma once\n")
        f.write(f"#include <stdint.h>\n")
        f.write(f"#define {guard}_W {w}\n")
        f.write(f"#define {guard}_H {h}\n")
        f.write(f"extern const uint8_t {name}_rgba[{n}];\n")

    # --- source ---
    cpath = out_dir / f"{name}.c"
    with open(cpath, "w") as f:
        f.write(f"/* Auto-generated by tools/gen_pico_atlases.py — do not edit */\n")
        f.write(f'#include "{name}.h"\n')
        f.write(f"\n")
        f.write(f"const uint8_t {name}_rgba[{n}] = {{\n")
        for i in range(0, n, BYTES_PER_LINE):
            chunk = data[i : i + BYTES_PER_LINE]
            f.write("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")

    print(f"  {name:30s}  {w:4d}×{h:3d}  {n/1024:7.1f} KB  → {cpath.name}")
    return n


def gen_central_header(names: list, out_dir: Path) -> None:
    hpath = out_dir / "pico_atlases.h"
    with open(hpath, "w") as f:
        f.write("/* Auto-generated by tools/gen_pico_atlases.py — do not edit */\n")
        f.write("#pragma once\n")
        for n in names:
            f.write(f'#include "{n}.h"\n')
    print(f"\n  {'pico_atlases.h':30s}  (central include)")


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python3 tools/gen_pico_atlases.py <project_root>")
        sys.exit(1)

    root    = Path(sys.argv[1]).resolve()
    out_dir = root / "src" / "pico_assets"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating Pico atlas C arrays in {out_dir}\n")
    print(f"  {'Name':30s}  {'Size':>10s}  {'KiB':>9s}")
    print(f"  {'-'*60}")

    total_bytes = 0
    names       = []

    for name, rel_png in ATLASES:
        src_png = root / rel_png
        if not src_png.exists():
            print(f"  WARNING: {src_png} not found — skipping")
            continue
        total_bytes += gen_atlas(name, src_png, out_dir)
        names.append(name)

    gen_central_header(names, out_dir)

    pico_flash_kb = 2048
    print(f"\n  Atlas flash usage : {total_bytes/1024:7.1f} KB")
    print(f"  Pico flash budget : {pico_flash_kb:7d} KB")
    remaining = pico_flash_kb - total_bytes / 1024
    if remaining < 400:
        print(f"  WARNING: only {remaining:.0f} KB left for program code!")
    else:
        print(f"  Remaining for code: {remaining:7.1f} KB  ✓")


if __name__ == "__main__":
    main()
